# Generated by Django 5.1.2 on 2025-08-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trend_monitoring", "0002_rna_seqc_rnaseq_metrics_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant_calling_metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("het_hom_variant_ratio", models.FloatField(null=True)),
                ("pct_gq0_variants", models.FloatField()),
                ("total_gq0_variants", models.IntegerField()),
                ("total_het_depth", models.IntegerField()),
                ("total_snps", models.IntegerField()),
                ("num_in_db_snp", models.IntegerField()),
                ("novel_snps", models.IntegerField()),
                ("filtered_snps", models.IntegerField()),
                ("pct_dbsnp", models.FloatField()),
                ("dbsnp_titv", models.FloatField()),
                ("novel_titv", models.FloatField()),
                ("total_indels", models.IntegerField()),
                ("novel_indels", models.IntegerField()),
                ("filtered_indels", models.IntegerField()),
                ("pct_dbsnp_indels", models.FloatField()),
                ("num_in_db_snp_indels", models.IntegerField()),
                ("dbsnp_ins_del_ratio", models.FloatField()),
                ("novel_ins_del_ratio", models.FloatField()),
                ("total_multiallelic_snps", models.IntegerField()),
                ("num_in_db_snp_multiallelic", models.IntegerField()),
                ("total_complex_indels", models.IntegerField()),
                ("num_in_db_snp_complex_indels", models.IntegerField()),
                ("snp_reference_bias", models.FloatField()),
                ("num_singletons", models.IntegerField()),
                ("total_called_variants", models.IntegerField()),
                ("total_called_variants_known", models.IntegerField()),
                ("total_called_variants_novel", models.IntegerField()),
            ],
            options={
                "db_table": "variant_calling_metrics",
            },
        ),
        migrations.AlterField(
            model_name="rna_seqc",
            name="average_fragment_length",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="picard",
            name="variant_calling_metrics",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trend_monitoring.variant_calling_metrics",
            ),
        ),
    ]
