# Generated by Django 6.0.4 on 2026-06-05 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_monitoring', '0002_rna_seqc_rnaseq_metrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sex_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.BooleanField(null=True)),
                ('reported_sex', models.CharField(max_length=5)),
                ('predicted_sex', models.CharField(max_length=5)),
                ('score', models.FloatField()),
                ('mapped_chrY', models.FloatField()),
                ('mapped_chr1', models.FloatField()),
            ],
            options={
                'db_table': 'sex_check',
            },
        ),
        migrations.RemoveField(
            model_name='report_sample',
            name='somalier_data',
        ),
        migrations.CreateModel(
            name='PlotAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report_sample',
            name='sex_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trend_monitoring.sex_check'),
        ),
        migrations.DeleteModel(
            name='Somalier_data',
        ),
    ]
